/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.net.ServerSocket;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Angazovanje;
import model.Predmet;
import model.Profesor;
import model.VrstaAngazovanja;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author vanja
 */
public class DodajAngForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajAngForma
     */
    public DodajAngForma() {
        initComponents();
        popuniComboboxeve();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxVrsta = new javax.swing.JComboBox<>();
        jComboBoxPredmet = new javax.swing.JComboBox<>();
        jComboBoxProfesor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("profesor");

        jLabel2.setText("predmet");

        jLabel3.setText("vrsta");

        jButton1.setText("Kreiraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxVrsta, 0, 162, Short.MAX_VALUE)
                    .addComponent(jComboBoxPredmet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Predmet predmet = (Predmet) jComboBoxPredmet.getSelectedItem();
        Profesor prof = (Profesor) jComboBoxProfesor.getSelectedItem();
        VrstaAngazovanja va = VrstaAngazovanja.valueOf( (String)jComboBoxVrsta.getSelectedItem()) ;
        
        Angazovanje a = new Angazovanje(-1, prof, predmet, va);
        KlijentskiZahtev kz= new KlijentskiZahtev(Operacije.DODAJ_ANGAZOVANJE, a);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean uspeh = (boolean) so.getOdgovor();
        if(uspeh){
            JOptionPane.showMessageDialog(null, "USPEH");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "GRESKA");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmet;
    private javax.swing.JComboBox<Profesor> jComboBoxProfesor;
    private javax.swing.JComboBox<String> jComboBoxVrsta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void popuniComboboxeve() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_PREDMETE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);        
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();         
        List<Predmet> sviPredmeti =(List<Predmet>) so.getOdgovor();
        jComboBoxPredmet.removeAllItems();
        for (Predmet p : sviPredmeti) {
            jComboBoxPredmet.addItem(p);
        }
        
         KlijentskiZahtev kz1 = new KlijentskiZahtev(Operacije.VRATI_PROFESORE, null);
        Komunikacija.getInstance().posaljiZahtev(kz1);        
         ServerskiOdgovor so1 = komunikacija.Komunikacija.getInstance().primiOdgovor();     
         List<Profesor> sviProfesori = (List<Profesor>) so1.getOdgovor() ;
        jComboBoxProfesor.removeAllItems();
        for (Profesor pr : sviProfesori) {
            jComboBoxProfesor.addItem(pr);
        }
        
        jComboBoxVrsta.removeAllItems();
        for(VrstaAngazovanja va: VrstaAngazovanja.values()){
            jComboBoxVrsta.addItem(va.toString());
        }
        
        
        
        
        
        
    }
}
