/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.model.ModelTabeleAngazovanja;
import forme.model.ModelTabeleAngazovanja2;
import java.util.ArrayList;
import java.util.List;
import javax.crypto.KEM;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Angazovanje;
import model.Predmet;
import model.Profesor;
import model.VrstaAngazovanja;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;
import operacije.Operacije;

/**
 *
 * @author vanja
 */
public class GlavnaForma extends javax.swing.JFrame {
    private Profesor ulogovani;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(Profesor ulogovani) {
        this.ulogovani=ulogovani;
        initComponents();
        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelBrojacUkupno = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelBrojacPredavanja = new javax.swing.JLabel();
        jLabelBrojacVezbe = new javax.swing.JLabel();
        jLabelBrojacLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAngazovanja = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOstaliProfesori = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonPrikaziOstaleProfesore = new javax.swing.JButton();
        jButtonObrisiAngazovanje = new javax.swing.JButton();
        jButtonKreirajAngazovanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci profila"));

        jLabel1.setText("email");

        jLabelEmail.setText("jLabel2");

        jLabel2.setText("ime");

        jLabel3.setText("prezime");

        jLabelIme.setText("jLabel4");

        jLabelPrezime.setText("jLabel4");

        jLabel4.setText("ukupan br angazovanja");

        jLabelBrojacUkupno.setText("lavel");

        jLabel5.setText("LAB");

        jLabel6.setText("VEZBE");

        jLabel7.setText("PREDAVANJA");

        jLabelBrojacPredavanja.setText("jLabel8");

        jLabelBrojacVezbe.setText("jLabel8");

        jLabelBrojacLab.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelIme, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBrojacUkupno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelBrojacLab))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelBrojacVezbe))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(48, 48, 48)
                                .addComponent(jLabelBrojacPredavanja)))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelBrojacUkupno, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabelBrojacPredavanja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelBrojacVezbe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelBrojacLab)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelIme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelPrezime))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelEmail))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTableAngazovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAngazovanja);

        jTableOstaliProfesori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableOstaliProfesori);

        jLabel8.setText("Sva angazovanja ulogovanog profesora");

        jLabel9.setText("Svi profesori na odabranom predmetu");

        jButtonPrikaziOstaleProfesore.setText("prikazi ostale profesore");
        jButtonPrikaziOstaleProfesore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziOstaleProfesoreActionPerformed(evt);
            }
        });

        jButtonObrisiAngazovanje.setText("obrisi angazovanje");
        jButtonObrisiAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiAngazovanjeActionPerformed(evt);
            }
        });

        jButtonKreirajAngazovanje.setText("kreiraj");
        jButtonKreirajAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajAngazovanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPrikaziOstaleProfesore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonObrisiAngazovanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonKreirajAngazovanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPrikaziOstaleProfesore, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonObrisiAngazovanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKreirajAngazovanje)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziOstaleProfesoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziOstaleProfesoreActionPerformed
        int selektovaniRed = jTableAngazovanja.getSelectedRow();
        if(selektovaniRed!=-1){
             ModelTabeleAngazovanja mta = (ModelTabeleAngazovanja) jTableAngazovanja.getModel();
             Angazovanje a = mta.getLista().get(selektovaniRed);
             Predmet p = a.getPredmet();
             
            KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.VRATI_ANGAZOVANJA_PREDMETA,p) ;
            Komunikacija.getInstance().posaljiZahtev(kz);
        
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
             List<Angazovanje> lista  = (List<Angazovanje>) so.getOdgovor();
            
            ModelTabeleAngazovanja2 mta2 = new ModelTabeleAngazovanja2(lista);
             jTableOstaliProfesori.setModel(mta2);
             
             
        } 
    }//GEN-LAST:event_jButtonPrikaziOstaleProfesoreActionPerformed

    private void jButtonObrisiAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiAngazovanjeActionPerformed
        int selektovaniRed = jTableOstaliProfesori.getSelectedRow();
        if(selektovaniRed!=-1){
             ModelTabeleAngazovanja2 mta = (ModelTabeleAngazovanja2) jTableOstaliProfesori.getModel();
             Angazovanje a = mta.getLista().get(selektovaniRed);
             
             KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.OBRISI_ANGAZOVANJE, a);
             Komunikacija.getInstance().posaljiZahtev(kz);
             
             ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
             boolean uspeh = (boolean) so.getOdgovor();
             if(uspeh){
                 JOptionPane.showMessageDialog(null, "USPEH");
                 popuniFormu();
                 ModelTabeleAngazovanja2 mta2= new ModelTabeleAngazovanja2(new ArrayList<>());
                 jTableOstaliProfesori.setModel(mta2);
             }else{
                 JOptionPane.showMessageDialog(null, "GRESKA");
             }
        }
    }//GEN-LAST:event_jButtonObrisiAngazovanjeActionPerformed

    private void jButtonKreirajAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajAngazovanjeActionPerformed
        DodajAngForma f=  new DodajAngForma();
        f.setVisible(true);
        ModelTabeleAngazovanja2 mta2= new ModelTabeleAngazovanja2(new ArrayList<>());
        jTableOstaliProfesori.setModel(mta2);
    }//GEN-LAST:event_jButtonKreirajAngazovanjeActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreirajAngazovanje;
    private javax.swing.JButton jButtonObrisiAngazovanje;
    private javax.swing.JButton jButtonPrikaziOstaleProfesore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBrojacLab;
    private javax.swing.JLabel jLabelBrojacPredavanja;
    private javax.swing.JLabel jLabelBrojacUkupno;
    private javax.swing.JLabel jLabelBrojacVezbe;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAngazovanja;
    private javax.swing.JTable jTableOstaliProfesori;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() {
        jLabelIme.setText(ulogovani.getIme());
        jLabelPrezime.setText(ulogovani.getPrezime());
        jLabelEmail.setText(ulogovani.getEmail());
        
        KlijentskiZahtev kz =  new KlijentskiZahtev(Operacije.VRATI_ANGAZOVANJA_PROFESORA, ulogovani);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<Angazovanje> lista  = (List<Angazovanje>) so.getOdgovor();
        
        int brojacUkupno= lista.size();
        int brojacP = 0;
        int brojacV=0;
        int brojacL=0;
        for (Angazovanje a : lista) {
            if(a.getVrsta().equals(VrstaAngazovanja.PREDAVANJA)){
                brojacP++;
            }else if(a.getVrsta().equals(VrstaAngazovanja.VEZBE)){
                brojacV++;
            }else{
                brojacL++;
            }
        }
        jLabelBrojacUkupno.setText(brojacUkupno+"");
        jLabelBrojacPredavanja.setText(brojacP+"");
        jLabelBrojacVezbe.setText(brojacV+"");
        jLabelBrojacLab.setText(brojacL+"");
        
        ModelTabeleAngazovanja mta = new ModelTabeleAngazovanja(lista);
        jTableAngazovanja.setModel(mta);
    }
}
