/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

 
import forme.model.ModelTabeleProfesor;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Angazovanje;
import model.Korisnik;
import model.Predmet;
import model.Profesor;
import model.Zvanje;
import operacije.Operacije;
import tranfser.KlijentskiZahtev;
import tranfser.ServerskiOdgovor;

/**
 *
 * @author vanja
 */
public class KlijentskaForma extends javax.swing.JFrame {
    private Korisnik ulogovaniKorisnik;
    private Profesor p;
    private List<Angazovanje> angazovanja = new ArrayList<>();
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(Korisnik k) {
        initComponents();
        this.ulogovaniKorisnik=k;
        jLabelIme.setText(k.getIme());
        jLabelPrezime.setText(k.getPrezime());
        jComboBoxZvanje.removeAllItems();
        Zvanje[] zvanja = Zvanje.values();
        for (Zvanje z : zvanja) {
            jComboBoxZvanje.addItem(z.toString());
        }
        popunitabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldprezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxZvanje = new javax.swing.JComboBox<>();
        jButtonDodajProfesora = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNazivPredmeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEsp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldkod = new javax.swing.JTextField();
        jButtonDodajPredmet = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfesori = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIme.setText("jLabel1");

        jLabelPrezime.setText("jLabel1");

        jLabel1.setText("ime");

        jTextFieldIme.setText("marko");

        jLabel2.setText("prezime");

        jTextFieldprezime.setText("markovic");
        jTextFieldprezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldprezimeActionPerformed(evt);
            }
        });

        jLabel3.setText("Zvanje");

        jComboBoxZvanje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonDodajProfesora.setText("dodaj profesora");
        jButtonDodajProfesora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajProfesoraActionPerformed(evt);
            }
        });

        jLabel4.setText("nazivPredmeta");

        jTextFieldNazivPredmeta.setText("programiranje 1");

        jLabel5.setText("esp");

        jTextFieldEsp.setText("5");

        jLabel6.setText("kod");

        jTextFieldkod.setText("p1");

        jButtonDodajPredmet.setText("dodaj predmet");
        jButtonDodajPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPredmetActionPerformed(evt);
            }
        });

        jLabel7.setText("unos profesora");

        jLabel8.setText("unos predmeta");

        jTableProfesori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProfesori);

        jButton1.setText("angazovanja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jButtonDodajProfesora))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldprezime)
                                    .addComponent(jComboBoxZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(jTextFieldNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldEsp)
                                            .addComponent(jTextFieldkod, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jButtonDodajPredmet))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(240, 240, 240)
                        .addComponent(jLabelIme)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelPrezime)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIme)
                    .addComponent(jLabelPrezime)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDodajPredmet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldprezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDodajProfesora)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldprezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldprezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprezimeActionPerformed

    private void jButtonDodajProfesoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajProfesoraActionPerformed
         String ime = jTextFieldIme.getText();
         String prezime = jTextFieldprezime.getText();
         String strZvanje = (String) jComboBoxZvanje.getSelectedItem();
         Zvanje zvanje = Zvanje.valueOf(strZvanje);
         
          p = new Profesor(-1, ime, prezime, zvanje, ulogovaniKorisnik.getEmail());
         KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.DODAJ_PROF, p);
         Komunikacija.getInstance().posaljiZahtev(kz);
         
         
         ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
         p = (Profesor) so.getOdgovor();
         if(p==null){
             JOptionPane.showMessageDialog(this, "GRESKA PRI UNOSU");
         }else{
             JOptionPane.showMessageDialog(this, "USPESNO UNETO");
             popunitabelu();
         } 
    }//GEN-LAST:event_jButtonDodajProfesoraActionPerformed

    private void jButtonDodajPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPredmetActionPerformed
        String naziv = jTextFieldNazivPredmeta.getText();
        int esp  = Integer.parseInt(jTextFieldEsp.getText());
        String kod = jTextFieldkod.getText();
        
        
        Predmet p = new Predmet(-1, naziv, kod, esp);
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.DODAJ_PREDMET, p);
        Komunikacija.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean uspesno = (boolean) so.getOdgovor();
        if(uspesno){
            JOptionPane.showMessageDialog(this, "USPESNO UNETO");
        }else{
             JOptionPane.showMessageDialog(this, "GRESKA PRI UNOSU");
        }
//        
        
        
        
    }//GEN-LAST:event_jButtonDodajPredmetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int selektovaniRed = jTableProfesori.getSelectedRow();
         if(selektovaniRed==-1){
               JOptionPane.showMessageDialog(this, "NISTE ODABRALI PROFESORA");
               return;
         }
         ModelTabeleProfesor mtp = (ModelTabeleProfesor) jTableProfesori.getModel();
         Profesor p=mtp.getLista().get(selektovaniRed);
         UnosAngazovanjaForma1 uaf = new UnosAngazovanjaForma1(this, false, p,ulogovaniKorisnik);
         uaf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDodajPredmet;
    private javax.swing.JButton jButtonDodajProfesora;
    private javax.swing.JComboBox<String> jComboBoxZvanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfesori;
    private javax.swing.JTextField jTextFieldEsp;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldNazivPredmeta;
    private javax.swing.JTextField jTextFieldkod;
    private javax.swing.JTextField jTextFieldprezime;
    // End of variables declaration//GEN-END:variables

    private void popunitabelu() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.UCITAJ_PROFESORE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
                
        List<Profesor> lista = (List<Profesor>) so.getOdgovor();
        ModelTabeleProfesor mtp = new ModelTabeleProfesor(lista);
        jTableProfesori.setModel(mtp); 
    }
}
