/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import forme.model.ModelTabeleAngazovanje;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Angazovanje;
import model.Korisnik;
import model.Predmet;
import model.Profesor;
import operacije.Operacije;
import tranfser.KlijentskiZahtev;
import tranfser.ServerskiOdgovor;

/**
 *
 * @author vanja
 */
public class UnosAngazovanjaForma1 extends javax.swing.JDialog {
    private Profesor p;
    private Korisnik ulogovaniKorisnik;
    /**
     * Creates new form UnosAngazovanjaForma1
     */
    public UnosAngazovanjaForma1(java.awt.Frame parent, boolean modal,
            Profesor p,Korisnik ulogovaniKorisnik) {
        super(parent, modal);
        initComponents();
        this.p=p;
        this.ulogovaniKorisnik=ulogovaniKorisnik;
       // System.out.println(p);
       //  System.out.println(ulogovaniKorisnik);
        popuniCombobox();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxPredmeti = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAngazovanja = new javax.swing.JTable();
        jButtonSACUVAJUBAZI = new javax.swing.JButton();
        jButtonObrisiAngazovanje = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("predmeti");

        jButton1.setText("dodaj angazovanje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableAngazovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAngazovanja);

        jButtonSACUVAJUBAZI.setText("sacuvaj promene u bazi");
        jButtonSACUVAJUBAZI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSACUVAJUBAZIActionPerformed(evt);
            }
        });

        jButtonObrisiAngazovanje.setText("obrisi angazovanje");
        jButtonObrisiAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiAngazovanjeActionPerformed(evt);
            }
        });

        jButtonAzuriraj.setText("azuriraj angazovanje");
        jButtonAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBoxPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonObrisiAngazovanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAzuriraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSACUVAJUBAZI)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButtonObrisiAngazovanje)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAzuriraj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButtonSACUVAJUBAZI)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ModelTabeleAngazovanje mta = (ModelTabeleAngazovanje) jTableAngazovanja.getModel();
        if(mta.getLista().size()>=3){
            JOptionPane.showMessageDialog(this, "NE MOZE DA SE DODA, VEC IMA 3");
            return;
        }
        Date datum = new Date();
       // Profesor p;
        Predmet predmet = (Predmet) jComboBoxPredmeti.getSelectedItem();
        String email = ulogovaniKorisnik.getEmail();
        
        Angazovanje a = new Angazovanje(-1,datum,p,predmet,email);
        
       
        mta.dodaj(a);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSACUVAJUBAZIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSACUVAJUBAZIActionPerformed
         ModelTabeleAngazovanje mta = (ModelTabeleAngazovanje) jTableAngazovanja.getModel();
         List<Angazovanje> lista = mta.getLista();
         
         KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.SACUVAJ_ANGAZOVANJA, lista);
         Komunikacija.getInstance().posaljiZahtev(kz);
         
         ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
         boolean uspeh = (boolean) so.getOdgovor();
         if(uspeh){
              JOptionPane.showMessageDialog(this, "USPESNO AZURIRANO");
              popuniTabelu();
         }else{
             JOptionPane.showMessageDialog(this, "GRESKA");
         }
    }//GEN-LAST:event_jButtonSACUVAJUBAZIActionPerformed

    private void jButtonObrisiAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiAngazovanjeActionPerformed
        int selektovaniRed=  jTableAngazovanja.getSelectedRow();
        if(selektovaniRed==-1){
             JOptionPane.showMessageDialog(this, "MORAS DA SELEKTUJES RED");
            return;
        }
          ModelTabeleAngazovanje mta = (ModelTabeleAngazovanje) jTableAngazovanja.getModel();
        mta.obrisi(selektovaniRed);
        
        
    }//GEN-LAST:event_jButtonObrisiAngazovanjeActionPerformed

    private void jButtonAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzurirajActionPerformed
         int selektovaniRed=  jTableAngazovanja.getSelectedRow();
        if(selektovaniRed==-1){
             JOptionPane.showMessageDialog(this, "MORAS DA SELEKTUJES RED");
            return;
        }
           ModelTabeleAngazovanje mta = (ModelTabeleAngazovanje) jTableAngazovanja.getModel();
           Angazovanje a = mta.getLista().get(selektovaniRed);
           AzurirajAngazovanje aa = new AzurirajAngazovanje(this, false, a);
           aa.setVisible(true);
           
           mta.osveziTabelu();
    }//GEN-LAST:event_jButtonAzurirajActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonObrisiAngazovanje;
    private javax.swing.JButton jButtonSACUVAJUBAZI;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmeti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAngazovanja;
    // End of variables declaration//GEN-END:variables

    private void popuniCombobox() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.UCITAJ_PREDMETE, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
                
        List<Predmet> lista = (List<Predmet>) so.getOdgovor();
        for (Predmet p : lista) {
            jComboBoxPredmeti.addItem(p);
        } 
        
    }

    private void popuniTabelu() {
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.UCITAJ_ANGAZOVANJA, p);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
         List<Angazovanje> lista = (List<Angazovanje>) so.getOdgovor();
         
         ModelTabeleAngazovanje mta =  new ModelTabeleAngazovanje(lista);
         jTableAngazovanja.setModel(mta);
        
    }

    void azurirajAngazovanje(Angazovanje a) {
        ModelTabeleAngazovanje mta =  (ModelTabeleAngazovanje) jTableAngazovanja.getModel();
        mta.azuirajAngazovanje(a);
        
    }
}
