/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.model.ModelTabeleIgra;
import model.Igra;
import niti.BrojNit;
import tranfser.KlijentskiZahtev;
import tranfser.ServerskiOdgovor;

/**
 *
 * @author vanja
 */
public class KlijentskaForma extends javax.swing.JFrame {
    BrojNit nit1;
     BrojNit nit2;
      BrojNit nit3;
       BrojNit nit4;
    private int brojPokusaja=0;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        ModelTabeleIgra mti = new ModelTabeleIgra();
        jTableIgra.setModel(mti); 
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBRoj1 = new javax.swing.JLabel();
        jLabelBRoj2 = new javax.swing.JLabel();
        jLabelBRoj3 = new javax.swing.JLabel();
        jLabelBRoj4 = new javax.swing.JLabel();
        jButtonstart1 = new javax.swing.JButton();
        jButtonstop1 = new javax.swing.JButton();
        jButtonstop2 = new javax.swing.JButton();
        jButtonstart2 = new javax.swing.JButton();
        jButtonstop3 = new javax.swing.JButton();
        jButtonstart3 = new javax.swing.JButton();
        jButtonstop4 = new javax.swing.JButton();
        jButtonstart4 = new javax.swing.JButton();
        jButtonPosalji = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNaMestu = new javax.swing.JLabel();
        jLabelVanMesta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIgra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBRoj1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBRoj1.setText("0");

        jLabelBRoj2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBRoj2.setText("0");

        jLabelBRoj3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBRoj3.setText("0");

        jLabelBRoj4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBRoj4.setText("0");

        jButtonstart1.setText("start 1");
        jButtonstart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstart1ActionPerformed(evt);
            }
        });

        jButtonstop1.setText("stop 1");
        jButtonstop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstop1ActionPerformed(evt);
            }
        });

        jButtonstop2.setText("stop 2");
        jButtonstop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstop2ActionPerformed(evt);
            }
        });

        jButtonstart2.setText("start 2");
        jButtonstart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstart2ActionPerformed(evt);
            }
        });

        jButtonstop3.setText("stop 3");
        jButtonstop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstop3ActionPerformed(evt);
            }
        });

        jButtonstart3.setText("start 3");
        jButtonstart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstart3ActionPerformed(evt);
            }
        });

        jButtonstop4.setText("stop 4");
        jButtonstop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstop4ActionPerformed(evt);
            }
        });

        jButtonstart4.setText("start 4");
        jButtonstart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstart4ActionPerformed(evt);
            }
        });

        jButtonPosalji.setText("posalji");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jLabel1.setText("NA MESTU");

        jLabel2.setText("NISU NA MESTU");

        jTableIgra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIgra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelBRoj1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonstop1)
                            .addComponent(jButtonstart1)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonstop2)
                                .addComponent(jButtonstart2))
                            .addComponent(jLabelBRoj2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonstop3)
                                    .addComponent(jButtonstart3))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBRoj3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonstop4)
                            .addComponent(jButtonstart4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabelBRoj4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jButtonPosalji)))
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVanMesta)
                            .addComponent(jLabelNaMestu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonstart4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelBRoj4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jButtonPosalji)))
                                .addGap(33, 33, 33)
                                .addComponent(jButtonstop4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonstart3)
                                .addGap(133, 133, 133)
                                .addComponent(jButtonstop3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonstart2)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelBRoj2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelBRoj3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addComponent(jButtonstop2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonstart1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelBRoj1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jButtonstop1))))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNaMestu)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelVanMesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonstop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstop2ActionPerformed
         nit2.zaustaviNit();
    }//GEN-LAST:event_jButtonstop2ActionPerformed

    private void jButtonstart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstart1ActionPerformed
          nit1 = new BrojNit(jLabelBRoj1);
         nit1.start();
    }//GEN-LAST:event_jButtonstart1ActionPerformed

    private void jButtonstop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstop1ActionPerformed
        nit1.zaustaviNit();
    }//GEN-LAST:event_jButtonstop1ActionPerformed

    private void jButtonstart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstart2ActionPerformed
       nit2 = new BrojNit(jLabelBRoj2);
         nit2.start();
    }//GEN-LAST:event_jButtonstart2ActionPerformed

    private void jButtonstart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstart3ActionPerformed
       nit3 = new BrojNit(jLabelBRoj3);
         nit3.start();
    }//GEN-LAST:event_jButtonstart3ActionPerformed

    private void jButtonstop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstop3ActionPerformed
        nit3.zaustaviNit();
    }//GEN-LAST:event_jButtonstop3ActionPerformed

    private void jButtonstart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstart4ActionPerformed
        nit4 = new BrojNit(jLabelBRoj4);
         nit4.start();
    }//GEN-LAST:event_jButtonstart4ActionPerformed

    private void jButtonstop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstop4ActionPerformed
          nit4.zaustaviNit();
    }//GEN-LAST:event_jButtonstop4ActionPerformed

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
        if(brojPokusaja<=5){
            String kombinacija  =  jLabelBRoj1.getText()+"-"+jLabelBRoj2.getText()+"-"+
                     jLabelBRoj3.getText()+"-" +  jLabelBRoj4.getText();

            System.out.println(kombinacija);

            Igra igra = new Igra(-1, kombinacija, -1,-1);
            KlijentskiZahtev kz = new KlijentskiZahtev(operacije.Operacije.POGADJAJ, igra);
            komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);

            ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
            igra = (Igra) so.getOdgovor();
            brojPokusaja++;
            jLabelNaMestu.setText(igra.getBrPogodjenihNaMestu()+"");
            jLabelVanMesta.setText(igra.getBrPogodjenihNisuNaMestu()+"");
            /////
            ModelTabeleIgra mti = (ModelTabeleIgra) jTableIgra.getModel();
            mti.dodajIgru(igra);
        }else{
            System.out.println("NEMA VISE POKUSAJA");
        }
        
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JButton jButtonstart1;
    private javax.swing.JButton jButtonstart2;
    private javax.swing.JButton jButtonstart3;
    private javax.swing.JButton jButtonstart4;
    private javax.swing.JButton jButtonstop1;
    private javax.swing.JButton jButtonstop2;
    private javax.swing.JButton jButtonstop3;
    private javax.swing.JButton jButtonstop4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBRoj1;
    private javax.swing.JLabel jLabelBRoj2;
    private javax.swing.JLabel jLabelBRoj3;
    private javax.swing.JLabel jLabelBRoj4;
    private javax.swing.JLabel jLabelNaMestu;
    private javax.swing.JLabel jLabelVanMesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIgra;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        
    }
}
