/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Korisnik;
import model.Prevod;
import model.Rec;
import model.forme.ModelTabeleRecnik;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author vanja
 */
public class GlavnaForma extends javax.swing.JFrame {
    private Korisnik ulogovani;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(Korisnik ulogovani) {
        initComponents();
        this.ulogovani=ulogovani;
        
        popunitabelurecnik();
        jButtonUnesi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOdjava = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecnik = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPretraga = new javax.swing.JTextField();
        jButtonPosalji = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonUnesi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOdjava.setText("odjava");
        jButtonOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjavaActionPerformed(evt);
            }
        });

        jTableRecnik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRecnik);

        jLabel1.setText("pretraga");

        jButtonPosalji.setText("posalji");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButtonUnesi.setText("unesi");
        jButtonUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonPosalji)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUnesi, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(750, Short.MAX_VALUE)
                        .addComponent(jButtonOdjava)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOdjava)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPosalji))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUnesi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjavaActionPerformed
         
        
        KlijentskiZahtev kz =new KlijentskiZahtev(Operacije.LOGOUT, ulogovani);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean uspeh = (boolean) so.getOdgovor();
        if(uspeh){
            LoginForma lf = new LoginForma();
            lf.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "GRESKA");
        }
        
        
        
        
    }//GEN-LAST:event_jButtonOdjavaActionPerformed

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
       String unos = jTextFieldPretraga.getText();
       
       KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.PRETRAGA, unos);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        Rec r = (Rec) so.getOdgovor();
        if(r==null){
            JOptionPane.showMessageDialog(null, "GRESKA");
             jButtonUnesi.setVisible(true);
        }else{
              List<Prevod> prevodi =r.getPrevodi();
                String rezultat="";
                for (Prevod p : prevodi) {
                    rezultat+=p.getEngRec();
                    rezultat+=";";
                }
                jTextArea1.setText(rezultat);
        }
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    private void jButtonUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnesiActionPerformed
       String srp = jTextFieldPretraga.getText(); //macka
       String prevodi = jTextArea1.getText(); //cat;dsda;
       String[] nizPrevoda =  prevodi.split(";"); //{cat,dada}
        
       Rec rec = new Rec();
       rec.setSrpskaRec(srp); //macka
        List<Prevod> lista =  new ArrayList<>();
        for (String el : nizPrevoda) {
            Prevod p = new Prevod();
            p.setEngRec(el);
            p.setRec(rec);
            lista.add(p);
        }
         rec.setPrevodi(lista);
        
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.UNESI, rec);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean uspeh = (boolean) so.getOdgovor();
        if(uspeh){
            JOptionPane.showMessageDialog(null, "USPEH PRILIKOM UNOSA");
             popunitabelurecnik();
             jButtonUnesi.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(null, "GRESKA PRILIKOM UNOSA");
        }
       
        
    }//GEN-LAST:event_jButtonUnesiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdjava;
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JButton jButtonUnesi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRecnik;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldPretraga;
    // End of variables declaration//GEN-END:variables

    private void popunitabelurecnik() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.UCITAJ_RECNIK,null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        //
        ServerskiOdgovor so =Komunikacija.getInstance().primiOdgovor();
        List<Rec> lista = (List<Rec>) so.getOdgovor();
        
        ModelTabeleRecnik mtr = new ModelTabeleRecnik(lista);
        jTableRecnik.setModel(mtr);
    }
}
